version: '3'
services:
  # Mariadb config
  mariadb:
    build :
      context : ./requirements/MariaDB/.
      dockerfile : ./Dockerfile
    image : mariadb
    container_name: mariadb
    restart : always
    ports:
      - "3306::3306"
    volumes:
      - db_data:/var/lib/mysql/
    networks:
      - backend
    environment:
      - WP_DB=${WP_DB}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PWD=${MARIADB_USER_PWD}
    env_file :
      - .env

  nginx:
    build:
      context : ./requirements/nginx/.
      dockerfile : ./Dockerfile
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443::443"
    restart: always
    volumes:
      - wordpress:/var/www/html/
    networks:
      - backend
    env_file:
      - .env

  wordpress:
    build:
      context : ./requirements/wordpress/.
      dockerfile : ./Dockerfile
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000::9000"
      - "3306::3306"
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - backend
    env_file:
      - .env

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mderome/data/db_data
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/mderome/data/wp_data
      o: bind


